#!/usr/bin/env python3
"""YAML import/export helpers for skills-sync."""

import sys
from pathlib import Path
from typing import Any, Dict, List, Optional

try:
    import yaml
    HAS_YAML = True
except ImportError:
    HAS_YAML = False

YAML_TEMPLATE = """# Skills Metadata
# Generated by skills-sync
# Edit this file to manage which skills to restore
# Set 'enabled: false' to exclude a skill from restoration

version: 1
skills:
"""

YAML_SKILL_TEMPLATE = """  - name: {name}
    source: {source}
    source_type: {source_type}
    skill_path: {skill_path}
    enabled: {enabled}
"""

YAML_SKILL_WITH_PLUGIN_TEMPLATE = """  - name: {name}
    source: {source}
    source_type: {source_type}
    skill_path: {skill_path}
    plugin_name: {plugin_name}
    enabled: {enabled}
"""

RESTORE_SCRIPT_TEMPLATE = '''#!/usr/bin/env python3
"""Restore skills from a sibling skills.yaml file."""

import shutil
import subprocess
import sys
from dataclasses import dataclass
from pathlib import Path
from typing import Dict, List, Optional

try:
    import yaml
    HAS_YAML = True
except ImportError:
    HAS_YAML = False


@dataclass
class SkillInfo:
    name: str
    source: str
    source_type: str
    skill_path: str
    plugin_name: Optional[str] = None


def parse_yaml_simple(content: str) -> Dict[str, object]:
    result: Dict[str, object] = {"version": 1, "skills": []}
    current_skill = None

    for line in content.split("\\n"):
        stripped = line.strip()
        if not stripped or stripped.startswith("#"):
            continue
        if stripped.startswith("version:"):
            result["version"] = int(stripped.split(":")[1].strip())
            continue
        if stripped.startswith("- name:"):
            if current_skill:
                result["skills"].append(current_skill)
            current_skill = {
                "name": stripped.split(":", 1)[1].strip().strip('"'),
                "source": "",
                "source_type": "local",
                "skill_path": "",
                "plugin_name": None,
                "enabled": True,
            }
            continue
        if current_skill and ":" in stripped:
            key, value = stripped.split(":", 1)
            key = key.strip()
            value = value.strip().strip('"')
            if key == "source":
                current_skill["source"] = value if value != '""' else ""
            elif key == "source_type":
                current_skill["source_type"] = value
            elif key == "skill_path":
                current_skill["skill_path"] = value if value != '""' else ""
            elif key == "plugin_name":
                current_skill["plugin_name"] = value if value else None
            elif key == "enabled":
                current_skill["enabled"] = value.lower() == "true"

    if current_skill:
        result["skills"].append(current_skill)

    return result


def load_from_yaml(yaml_path: Path) -> List[Dict[str, object]]:
    if not yaml_path.exists():
        print(f"Error: YAML file not found: {yaml_path}", file=sys.stderr)
        sys.exit(1)

    content = yaml_path.read_text(encoding="utf-8")
    if HAS_YAML:
        data = yaml.safe_load(content)
    else:
        data = parse_yaml_simple(content)

    skills = data.get("skills", [])
    return [skill for skill in skills if skill.get("enabled", True)]


def check_npx_available() -> bool:
    return shutil.which("npx") is not None


def run_command(cmd: List[str], description: str) -> bool:
    print(f"\\n{'=' * 60}")
    print(f"Executing: {description}")
    print(f"Command: {' '.join(cmd)}")
    print("=" * 60)

    try:
        result = subprocess.run(cmd, check=False)
        if result.returncode == 0:
            print(f"[OK] {description} completed")
            return True
        print(f"[FAILED] {description} (exit code: {result.returncode})")
        return False
    except FileNotFoundError:
        print(f"[FAILED] Command not found: {cmd[0]}")
        return False
    except Exception as exc:
        print(f"[FAILED] Error: {exc}")
        return False


def restore_all_skills(skills_to_restore: List[SkillInfo]) -> Dict[str, bool]:
    results: Dict[str, bool] = {}

    registry_skills = [skill for skill in skills_to_restore if skill.source_type == "registry"]
    github_skills = [skill for skill in skills_to_restore if skill.source_type == "github"]
    local_skills = [skill for skill in skills_to_restore if skill.source_type == "local"]

    print("\\n" + "=" * 60)
    print("Skills Restore")
    print("=" * 60)
    print(f"Installing {len(skills_to_restore)} skill(s):")
    for skill in skills_to_restore:
        print(f"  - {skill.name} ({skill.source_type}: {skill.source or 'n/a'})")
    print("=" * 60)

    if local_skills:
        print("\\n[WARNING] The following local-only skills cannot be auto-restored:")
        for skill in local_skills:
            print(f"  - {skill.name}")
            results[skill.name] = False
        print("Please back up these skills manually.\\n")

    restorable = registry_skills + github_skills
    if not restorable:
        print("\\nNo restorable skills found.")
        return results

    if not check_npx_available():
        print("\\n[FAILED] npx not found. Please install Node.js first.")
        print("  Download: https://nodejs.org/")
        sys.exit(1)

    registry_sources = {skill.source for skill in registry_skills}
    for source in registry_sources:
        source_skills = [skill for skill in registry_skills if skill.source == source]
        success = run_command(
            ["npx", "skills", "collection", "add", source, "-g", "-y"],
            f"Install collection: {source}",
        )
        for skill in source_skills:
            results[skill.name] = success

    github_repos: Dict[str, List[SkillInfo]] = {}
    for skill in github_skills:
        github_repos.setdefault(skill.source, []).append(skill)

    for repo, skills in github_repos.items():
        skill_names = [skill.name for skill in skills]
        success = run_command(
            ["npx", "skills", "add", repo, "-g", "-y", "--skill", *skill_names],
            f"Install from {repo}: {', '.join(skill_names)}",
        )
        for skill in skills:
            results[skill.name] = success

    return results


def print_summary(results: Dict[str, bool]) -> None:
    print("\\n" + "=" * 60)
    print("Installation Summary")
    print("=" * 60)

    success_count = sum(1 for success in results.values() if success)
    fail_count = len(results) - success_count

    for name, success in results.items():
        status = "[OK]" if success else "[FAILED]"
        print(f"  {status} {name}")

    print("-" * 60)
    print(f"Total: {success_count} succeeded, {fail_count} failed")
    print("=" * 60)

    if fail_count > 0:
        print("\\nTip: For failed skills, try manual installation:")
        print("  npx skills add <source> -g --skill <skill-name>")


def main() -> int:
    yaml_path = Path(__file__).with_name("skills.yaml")

    try:
        loaded_skills = load_from_yaml(yaml_path)
        if not loaded_skills:
            print("Error: No enabled skills found in YAML", file=sys.stderr)
            return 1

        skill_infos = [
            SkillInfo(
                name=skill["name"],
                source=skill.get("source", ""),
                source_type=skill.get("source_type", "local"),
                skill_path=skill.get("skill_path", ""),
                plugin_name=skill.get("plugin_name"),
            )
            for skill in loaded_skills
        ]

        results = restore_all_skills(skill_infos)
        print_summary(results)

        success_count = sum(1 for success in results.values() if success)
        if success_count == len(results):
            return 0
        if success_count > 0:
            return 1
        return 2
    except KeyboardInterrupt:
        print("\\n\\nOperation cancelled")
        return 130
    except Exception as exc:
        print(f"\\nError: {exc}")
        return 1


if __name__ == "__main__":
    sys.exit(main())
'''


def export_to_yaml(skills: List[Dict[str, Any]], output_path: Path) -> None:
    """Export skills to YAML file."""
    content = YAML_TEMPLATE

    for skill in skills:
        enabled = "true" if skill["source_type"] != "local" else "false"

        if skill.get("plugin_name"):
            content += YAML_SKILL_WITH_PLUGIN_TEMPLATE.format(
                name=skill["name"],
                source=skill["source"] or '""',
                source_type=skill["source_type"],
                skill_path=skill["skill_path"] or '""',
                plugin_name=skill["plugin_name"],
                enabled=enabled,
            )
        else:
            content += YAML_SKILL_TEMPLATE.format(
                name=skill["name"],
                source=skill["source"] or '""',
                source_type=skill["source_type"],
                skill_path=skill["skill_path"] or '""',
                enabled=enabled,
            )

    output_path.parent.mkdir(parents=True, exist_ok=True)
    with open(output_path, "w", encoding="utf-8") as f:
        f.write(content)

    print(f"[OK] YAML exported: {output_path}", file=sys.stderr)
    print(f"     Includes {len(skills)} skill(s)", file=sys.stderr)


def export_restore_script(script_path: Path) -> None:
    """Export a portable restore script beside the YAML file."""
    script_path.parent.mkdir(parents=True, exist_ok=True)
    with open(script_path, "w", encoding="utf-8") as f:
        f.write(RESTORE_SCRIPT_TEMPLATE)

    print(f"[OK] Restore script exported: {script_path}", file=sys.stderr)


def export_bundle(skills: List[Dict[str, Any]], output_path: Path) -> None:
    """Export both skills.yaml and a companion restore_skills.py script."""
    export_to_yaml(skills, output_path)
    export_restore_script(output_path.with_name("restore_skills.py"))


def parse_yaml_simple(content: str) -> Dict[str, Any]:
    """Simple YAML parser for skills.yaml when PyYAML is unavailable."""
    result: Dict[str, Any] = {"version": 1, "skills": []}
    current_skill: Optional[Dict[str, Any]] = None

    for line in content.split("\n"):
        stripped = line.strip()

        if not stripped or stripped.startswith("#"):
            continue

        if stripped.startswith("version:"):
            result["version"] = int(stripped.split(":")[1].strip())
            continue

        if stripped.startswith("- name:"):
            if current_skill:
                result["skills"].append(current_skill)
            current_skill = {
                "name": stripped.split(":", 1)[1].strip().strip('"'),
                "source": "",
                "source_type": "local",
                "skill_path": "",
                "plugin_name": None,
                "enabled": True,
            }
            continue

        if current_skill and ":" in stripped:
            key, value = stripped.split(":", 1)
            key = key.strip()
            value = value.strip().strip('"')

            if key == "source":
                current_skill["source"] = value if value != '""' else ""
            elif key == "source_type":
                current_skill["source_type"] = value
            elif key == "skill_path":
                current_skill["skill_path"] = value if value != '""' else ""
            elif key == "plugin_name":
                current_skill["plugin_name"] = value if value else None
            elif key == "enabled":
                current_skill["enabled"] = value.lower() == "true"

    if current_skill:
        result["skills"].append(current_skill)

    return result


def load_from_yaml(yaml_path: Path) -> List[Dict[str, Any]]:
    """Load enabled skills from YAML file."""
    if not yaml_path.exists():
        print(f"Error: YAML file not found: {yaml_path}", file=sys.stderr)
        sys.exit(1)

    with open(yaml_path, "r", encoding="utf-8") as f:
        content = f.read()

    if HAS_YAML:
        data = yaml.safe_load(content)
    else:
        data = parse_yaml_simple(content)

    skills = data.get("skills", [])
    return [skill for skill in skills if skill.get("enabled", True)]
