#!/usr/bin/env python3
"""YAML import/export helpers for skills-sync."""

import logging
import os
import shutil
import sys
import tempfile
from pathlib import Path
from typing import Any, Dict, List, Optional

yaml = None

try:
    import yaml

    HAS_YAML = True
except ImportError:
    HAS_YAML = False

logger = logging.getLogger("skills_sync")

YAML_TEMPLATE = """# Skills Metadata
# Generated by skills-sync
# Edit this file to manage which skills to restore
# Set 'enabled: false' to exclude a skill from restoration
# Note: source_type 'byted' uses a dedicated restore path

version: 1
skills:
"""

YAML_SKILL_TEMPLATE = """  - name: {name}
    source: {source}
    source_url: {source_url}
    source_type: {source_type}
    skill_path: {skill_path}
    enabled: {enabled}
"""

YAML_SKILL_WITH_PLUGIN_TEMPLATE = """  - name: {name}
    source: {source}
    source_url: {source_url}
    source_type: {source_type}
    skill_path: {skill_path}
    plugin_name: {plugin_name}
    enabled: {enabled}
"""


def parse_yaml_simple(content: str) -> Dict[str, Any]:
    """Simple YAML parser for skills.yaml when PyYAML is unavailable."""
    result: Dict[str, Any] = {"version": 1, "skills": []}
    current_skill: Optional[Dict[str, Any]] = None

    for line in content.split("\n"):
        stripped = line.strip()

        if not stripped or stripped.startswith("#"):
            continue

        if stripped.startswith("version:"):
            try:
                result["version"] = int(stripped.split(":", 1)[1].strip())
            except ValueError:
                logger.warning("Invalid version format, defaulting to 1")
                result["version"] = 1
            continue

        if stripped.startswith("- name:"):
            if current_skill:
                result["skills"].append(current_skill)
            current_skill = {
                "name": stripped.split(":", 1)[1].strip().strip('"'),
                "source": "",
                "source_url": "",
                "source_type": "local",
                "skill_path": "",
                "plugin_name": None,
                "enabled": True,
            }
            continue

        if current_skill and ":" in stripped:
            key, value = stripped.split(":", 1)
            key = key.strip()
            value = value.strip().strip('"')

            if key == "source":
                current_skill["source"] = value if value != '""' else ""
            elif key == "source_url":
                current_skill["source_url"] = value if value != '""' else ""
            elif key == "source_type":
                current_skill["source_type"] = value
            elif key == "skill_path":
                current_skill["skill_path"] = value if value != '""' else ""
            elif key == "plugin_name":
                current_skill["plugin_name"] = value if value else None
            elif key == "enabled":
                current_skill["enabled"] = value.lower() == "true"

    if current_skill:
        result["skills"].append(current_skill)

    return result


def load_from_yaml(yaml_path: Path) -> List[Dict[str, Any]]:
    """Load enabled skills from a YAML file.

    Args:
        yaml_path: Path to the YAML file

    Returns:
        List of enabled skill dictionaries

    Raises:
        FileNotFoundError: If the YAML file doesn't exist
        ValueError: If the YAML file is invalid
    """
    if not yaml_path.exists():
        raise FileNotFoundError(f"YAML file not found: {yaml_path}")

    try:
        content = yaml_path.read_text(encoding="utf-8")
    except OSError as e:
        raise ValueError(f"Failed to read YAML file: {e}") from e
    except UnicodeDecodeError as e:
        raise ValueError(f"YAML file is not valid UTF-8: {e}") from e

    try:
        if HAS_YAML:
            assert yaml is not None
            data = yaml.safe_load(content)
        else:
            data = parse_yaml_simple(content)
    except Exception as e:
        raise ValueError(f"Failed to parse YAML: {e}") from e

    if data is None:
        return []

    if not isinstance(data, dict):
        raise ValueError("YAML root must be a mapping")

    skills = data.get("skills", [])
    if not isinstance(skills, list):
        raise ValueError("'skills' must be a list")

    return [
        skill for skill in skills
        if isinstance(skill, dict) and skill.get("enabled", True)
    ]


def yaml_escape(value: str) -> str:
    """Escape a value for safe YAML output.

    Args:
        value: The string value to escape

    Returns:
        Escaped string safe for YAML
    """
    if not value:
        return '""'
    # Characters that require quoting in YAML
    special_chars = (
        ':', '#', '{', '}', '[', ']', ',', '&', '*', '?', '|',
        '-', '<', '>', '=', '!', '%', '@', '`', '"', "'", '\n', '\r', '\t'
    )
    needs_quote = any(c in value for c in special_chars)
    if needs_quote or value.startswith(' ') or value.endswith(' '):
        # Escape backslashes and double quotes, then wrap in quotes
        escaped = value.replace('\\', '\\\\').replace('"', '\\"')
        return f'"{escaped}"'
    return value


def export_to_yaml(skills: List[Dict[str, Any]], output_path: Path) -> None:
    """Export skills to a YAML file.

    Args:
        skills: List of skill dictionaries to export
        output_path: Path for the output YAML file

    Raises:
        OSError: If file write fails
    """
    content = YAML_TEMPLATE

    for skill in skills:
        enabled = "true" if skill["source_type"] != "local" else "false"
        name = yaml_escape(skill.get("name", ""))
        source = yaml_escape(skill.get("source", ""))
        source_url = yaml_escape(skill.get("source_url", ""))
        skill_path = yaml_escape(skill.get("skill_path", ""))

        if skill.get("plugin_name"):
            content += YAML_SKILL_WITH_PLUGIN_TEMPLATE.format(
                name=name,
                source=source,
                source_url=source_url,
                source_type=skill["source_type"],
                skill_path=skill_path,
                plugin_name=yaml_escape(skill["plugin_name"]),
                enabled=enabled,
            )
        else:
            content += YAML_SKILL_TEMPLATE.format(
                name=name,
                source=source,
                source_url=source_url,
                source_type=skill["source_type"],
                skill_path=skill_path,
                enabled=enabled,
            )

    output_path.parent.mkdir(parents=True, exist_ok=True)

    # Atomic write using temp file
    try:
        fd, temp_path = tempfile.mkstemp(
            dir=output_path.parent,
            prefix=".skills_yaml_",
            suffix=".tmp",
        )
        try:
            with os.fdopen(fd, "w", encoding="utf-8") as f:
                f.write(content)
            os.replace(temp_path, output_path)
        except Exception:
            if os.path.exists(temp_path):
                os.unlink(temp_path)
            raise
    except OSError as e:
        logger.error("Failed to write YAML file %s: %s", output_path, e)
        raise

    print(f"[OK] YAML exported: {output_path}", file=sys.stderr)
    print(f"     Includes {len(skills)} skill(s)", file=sys.stderr)


def export_restore_script(script_path: Path) -> None:
    """Export a portable restore script beside the YAML file.

    Args:
        script_path: Destination path for the restore script

    Raises:
        FileNotFoundError: If the template script doesn't exist
        OSError: If the copy fails
    """
    template_path = Path(__file__).with_name("restore_skills.py")
    if not template_path.exists():
        raise FileNotFoundError(f"Restore script template not found: {template_path}")

    script_path.parent.mkdir(parents=True, exist_ok=True)

    try:
        shutil.copy2(template_path, script_path)
    except OSError as e:
        logger.error("Failed to copy restore script to %s: %s", script_path, e)
        raise

    print(f"[OK] Restore script exported: {script_path}", file=sys.stderr)


def export_bundle(skills: List[Dict[str, Any]], output_path: Path) -> None:
    """Export both skills.yaml and a companion restore_skills.py script."""
    export_to_yaml(skills, output_path)
    export_restore_script(output_path.with_name("restore_skills.py"))
