#!/usr/bin/env python3
"""YAML import/export helpers for skills-sync."""

import shutil
import sys
from pathlib import Path
from typing import Any, Dict, List, Optional

yaml = None

try:
    import yaml

    HAS_YAML = True
except ImportError:
    HAS_YAML = False

YAML_TEMPLATE = """# Skills Metadata
# Generated by skills-sync
# Edit this file to manage which skills to restore
# Set 'enabled: false' to exclude a skill from restoration
# Note: source_type 'byted' uses a dedicated restore path via `npx skills add skills.byted.org/... --skill ...`

version: 1
skills:
"""

YAML_SKILL_TEMPLATE = """  - name: {name}
    source: {source}
    source_url: {source_url}
    source_type: {source_type}
    skill_path: {skill_path}
    enabled: {enabled}
"""

YAML_SKILL_WITH_PLUGIN_TEMPLATE = """  - name: {name}
    source: {source}
    source_url: {source_url}
    source_type: {source_type}
    skill_path: {skill_path}
    plugin_name: {plugin_name}
    enabled: {enabled}
"""


def parse_yaml_simple(content: str) -> Dict[str, Any]:
    """Simple YAML parser for skills.yaml when PyYAML is unavailable."""
    result: Dict[str, Any] = {"version": 1, "skills": []}
    current_skill: Optional[Dict[str, Any]] = None

    for line in content.split("\n"):
        stripped = line.strip()

        if not stripped or stripped.startswith("#"):
            continue

        if stripped.startswith("version:"):
            result["version"] = int(stripped.split(":", 1)[1].strip())
            continue

        if stripped.startswith("- name:"):
            if current_skill:
                result["skills"].append(current_skill)
            current_skill = {
                "name": stripped.split(":", 1)[1].strip().strip('"'),
                "source": "",
                "source_url": "",
                "source_type": "local",
                "skill_path": "",
                "plugin_name": None,
                "enabled": True,
            }
            continue

        if current_skill and ":" in stripped:
            key, value = stripped.split(":", 1)
            key = key.strip()
            value = value.strip().strip('"')

            if key == "source":
                current_skill["source"] = value if value != '""' else ""
            elif key == "source_url":
                current_skill["source_url"] = value if value != '""' else ""
            elif key == "source_type":
                current_skill["source_type"] = value
            elif key == "skill_path":
                current_skill["skill_path"] = value if value != '""' else ""
            elif key == "plugin_name":
                current_skill["plugin_name"] = value if value else None
            elif key == "enabled":
                current_skill["enabled"] = value.lower() == "true"

    if current_skill:
        result["skills"].append(current_skill)

    return result


def load_from_yaml(yaml_path: Path) -> List[Dict[str, Any]]:
    """Load enabled skills from a YAML file."""
    if not yaml_path.exists():
        print(f"Error: YAML file not found: {yaml_path}", file=sys.stderr)
        sys.exit(1)

    content = yaml_path.read_text(encoding="utf-8")
    if HAS_YAML:
        assert yaml is not None
        data = yaml.safe_load(content)
    else:
        data = parse_yaml_simple(content)

    skills = data.get("skills", []) if data else []
    return [skill for skill in skills if skill.get("enabled", True)]


def export_to_yaml(skills: List[Dict[str, Any]], output_path: Path) -> None:
    """Export skills to a YAML file."""
    content = YAML_TEMPLATE

    for skill in skills:
        enabled = "true" if skill["source_type"] != "local" else "false"

        if skill.get("plugin_name"):
            content += YAML_SKILL_WITH_PLUGIN_TEMPLATE.format(
                name=skill["name"],
                source=skill.get("source", "") or '""',
                source_url=skill.get("source_url", "") or '""',
                source_type=skill["source_type"],
                skill_path=skill.get("skill_path", "") or '""',
                plugin_name=skill["plugin_name"],
                enabled=enabled,
            )
        else:
            content += YAML_SKILL_TEMPLATE.format(
                name=skill["name"],
                source=skill.get("source", "") or '""',
                source_url=skill.get("source_url", "") or '""',
                source_type=skill["source_type"],
                skill_path=skill.get("skill_path", "") or '""',
                enabled=enabled,
            )

    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(content, encoding="utf-8")

    print(f"[OK] YAML exported: {output_path}", file=sys.stderr)
    print(f"     Includes {len(skills)} skill(s)", file=sys.stderr)


def export_restore_script(script_path: Path) -> None:
    """Export a portable restore script beside the YAML file."""
    template_path = Path(__file__).with_name("restore_skills.py")
    script_path.parent.mkdir(parents=True, exist_ok=True)
    shutil.copy2(template_path, script_path)
    print(f"[OK] Restore script exported: {script_path}", file=sys.stderr)


def export_bundle(skills: List[Dict[str, Any]], output_path: Path) -> None:
    """Export both skills.yaml and a companion restore_skills.py script."""
    export_to_yaml(skills, output_path)
    export_restore_script(output_path.with_name("restore_skills.py"))
